name: shop_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:

  cloud_firestore: ^4.3.0

  cupertino_icons: ^1.0.2
  firebase_auth:
  firebase_core: ^2.4.0
  image_picker: ^0.8.6
  firebase_storage: ^11.0.6
   
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  get:
  http:
  google_fonts: ^3.0.1
  get_storage :

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

    - assets/svgs/
    - assets/images/
    - icons/
